
package com.sheliming.ws.server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWSImpl", targetNamespace = "http://server.ws.sheliming.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWSImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://server.ws.sheliming.com/", className = "com.sheliming.ws.server.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://server.ws.sheliming.com/", className = "com.sheliming.ws.server.HelloResponse")
    @Action(input = "http://server.ws.sheliming.com/HelloWSImpl/helloRequest", output = "http://server.ws.sheliming.com/HelloWSImpl/helloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.sheliming.ws.server.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://server.ws.sheliming.com/", className = "com.sheliming.ws.server.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://server.ws.sheliming.com/", className = "com.sheliming.ws.server.GetUsersResponse")
    @Action(input = "http://server.ws.sheliming.com/HelloWSImpl/getUsersRequest", output = "http://server.ws.sheliming.com/HelloWSImpl/getUsersResponse")
    public List<User> getUsers();

}
